# Generated by Django 3.1.5 on 2021-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210130_1317'),
        ('wishlist', '0003_auto_20210214_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wished_item',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
